# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9437b833643fa51b62bb563e132cf9af99eb45addc4469fc2ca3d0d0e6d87ecdb723c9d2635af73d440ce9b67b2ac13bb3181cb794c98dff2fc6c6c5bbb0185

test:
  secret_key_base: 77ad999a3fc2e4c9a21084c2e66b084c9f280422445e08c906a41e2961658114ed25cf1ccde34e04b39cb2d931ef7b1590a898cf0bc8327d61a830276e479346

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
